#services:
#  mysqlDb:
#    image: 'mysql:latest'
##    container_name: 'spring-fb-db'
#    environment:
#      - 'MYSQL_DATABASE=mydatabase'
#      - 'MYSQL_PASSWORD=secret'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=myuser'
#    ports:
#      - "3306:3306"


version: '3.9'

services:
  kotlinapp:
    container_name: kotlinapp
    build: # this is the build context: .
      context: .
      dockerfile: Dockerfile
      args: # these are the arguments that are passed to the dockerfile
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports: # port exposed to the host machine
      - "8080:8080"
    environment: # these are the environment variables that are passed to the dockerfile
      DB_URL: jdbc:postgresql://db:5432/postgres
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on: # this is the dependency on the db service
      - db
  db:
    container_name: db
    image: postgres:12
    environment: # environment variables for the Postgres container
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: # port exposed to the host machine
      - "5432:5432"
    volumes: # volume used to persist data
      - pgdata:/var/lib/postgresql/data
#  mysqlDb:
#    image: 'mysql:latest'
#    #    container_name: 'spring-fb-db'
#    environment:
#      - 'MYSQL_DATABASE=mydatabase'
#      - 'MYSQL_PASSWORD=secret'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=myuser'
#    ports:
#      - "3306:3306"
#    volumes: # volume used to persist data
#      - pgdata:/var/lib/postgresql/data

volumes: # volume creation
  pgdata: {}