services:
  mysqlDb:
    image: 'mysql:latest'
#    container_name: 'spring-fb-db'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - "3306:3306"